# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for the study
start_date = '2010-01-01'
end_date = '2020-12-31'
time_range = a.Time(start_date, end_date)

# Define the wavelength of interest
wavelength = a.Wavelength(171 * u.angstrom)

# SoHO/EIT instrument details
soho_instrument = a.Instrument("EIT")
soho_query = Fido.search(time_range, soho_instrument, wavelength)

# SDO/AIA instrument details
sdo_instrument = a.Instrument("AIA")
sdo_query = Fido.search(time_range, sdo_instrument, wavelength)

# Display the query results for both instruments
print("Query for SoHO/EIT at 171 Å:")
print(soho_query)
print("Query for SDO/AIA at 171 Å:")
print(sdo_query)

# Uncomment the lines below to download the data
# soho_files = Fido.fetch(soho_query)
# sdo_files = Fido.fetch(sdo_query)
