# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a

# Define the time ranges for MDI and HMI observations based on the solar cycles
mdi_time_range_cycle_23 = a.Time('1996-05-01', '2008-04-30')
hmi_time_range_cycle_24 = a.Time('2008-05-01', '2017-04-30')

# Define the instrument and physical observable
mdi_instrument = a.Instrument("MDI")
hmi_instrument = a.Instrument("HMI")
physobs = a.Physobs("Doppler_velocity")

# Construct the queries for MDI and HMI
mdi_query_cycle_23 = Fido.search(mdi_time_range_cycle_23, mdi_instrument, physobs)
hmi_query_cycle_24 = Fido.search(hmi_time_range_cycle_24, hmi_instrument, physobs)

# Print the query results for MDI and HMI
print("Query for MDI observations during Solar Cycle 23:")
print(mdi_query_cycle_23)
print("Query for HMI observations during Solar Cycle 24:")
print(hmi_query_cycle_24)

# Define the time range for GONG observations post-MDI
gong_time_range_post_mdi = a.Time('2003-05-01', '2019-04-30')

# Define the instrument for GONG
gong_instrument = a.Instrument("GONG")

# Construct the query for GONG
gong_query_post_mdi = Fido.search(gong_time_range_post_mdi, gong_instrument, physobs)

# Print the query results for GONG
print("Query for GONG observations post-MDI:")
print(gong_query_post_mdi)

# Uncomment the lines below to download the data
# mdi_files_cycle_23 = Fido.fetch(mdi_query_cycle_23)
# hmi_files_cycle_24 = Fido.fetch(hmi_query_cycle_24)
# gong_files_post_mdi = Fido.fetch(gong_query_post_mdi)
