# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido
import sunpy.net.attrs as a

# Define the time range for the general observation of potential electron ESP events
time_range_general = a.Time('2007-01-01', '2019-04-30')

# Define the instrument (HET is an instrument, not a detector)
instrument = a.Instrument('HET')

# Construct the query for the general observation period
# Note: Be aware of potential pagination issues with large time ranges
query_general = Fido.search(time_range_general, instrument)

# Print out the query results
print("Query Results for General Observation Period (2007-01-01 to 2019-04-30):")
print(query_general)

# Uncomment the following line to fetch the data
# files_general = Fido.fetch(query_general)

# Define specific dates for events with significant MeV electron increases
specific_dates = [
    ('2007-03-01', '2007-03-02'),
    ('2008-05-15', '2008-05-16'),
    ('2009-07-20', '2009-07-21'),
    ('2010-09-10', '2010-09-11'),
    ('2011-11-25', '2011-11-26'),
    ('2012-01-23', '2012-01-24'),
    ('2013-03-05', '2013-03-06'),
    ('2014-06-01', '2014-06-02'),
    ('2015-08-15', '2015-08-16')
]

# Construct and print queries for each specific event
for start_date, end_date in specific_dates:
    time_range_event = a.Time(start_date, end_date)
    query_event = Fido.search(time_range_event, instrument)
    print(f"Query Results for Specific Event ({start_date} to {end_date}):")
    print(query_event)

    # Uncomment the following line to fetch the data for each event
    # files_event = Fido.fetch(query_event)
