# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# LASCO on SOHO: Observations of HCMEs during the rise phases of solar cycles 23, 24, and 25
lasco_time_range = a.Time('1996-01-01T00:00:00', '2022-12-31T23:59:59')
lasco_instrument = a.Instrument("LASCO")
lasco_query = Fido.search(lasco_time_range, lasco_instrument)

# AIA on SDO: Identification of solar sources for HCMEs in solar cycles 24 and 25
# Assuming the rise phase of solar cycle 24 started in 2008 and ended in 2014 for cycle 25
aia_time_range = a.Time('2008-01-01T00:00:00', '2022-12-31T23:59:59')
aia_instrument = a.Instrument("AIA")
aia_wavelength = a.Wavelength(171 * u.angstrom, 304 * u.angstrom)  # Typical EUV wavelengths
aia_query = Fido.search(aia_time_range, aia_instrument, aia_wavelength)

# SECCHI on STEREO: Confirmation of backside halo locations in solar cycles 24 and 25
secchi_time_range = a.Time('2008-01-01T00:00:00', '2022-12-31T23:59:59')
secchi_instrument = a.Instrument("SECCHI")
secchi_query = Fido.search(secchi_time_range, secchi_instrument)

# Display the query results
print("Query for LASCO data:")
print(lasco_query)
print("Query for AIA data:")
print(aia_query)
print("Query for SECCHI data:")
print(secchi_query)

# Uncomment the lines below to download the data
# lasco_files = Fido.fetch(lasco_query)
# aia_files = Fido.fetch(aia_query)
# secchi_files = Fido.fetch(secchi_query)
