# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period and instruments based on the context provided

# SDO/AIA observations
aia_time_range = a.Time('2013-05-13T13:30:00', '2013-05-13T18:30:00')
aia_wavelengths = (a.Wavelength(171*u.angstrom) | a.Wavelength(304*u.angstrom) | 
                   a.Wavelength(94*u.angstrom) | a.Wavelength(131*u.angstrom) | 
                   a.Wavelength(193*u.angstrom) | a.Wavelength(211*u.angstrom) | 
                   a.Wavelength(335*u.angstrom) | a.Wavelength(1600*u.angstrom) | 
                   a.Wavelength(1700*u.angstrom))
aia_instrument = a.Instrument('AIA')

# PROBA2/SWAP observations
swap_time_range = a.Time('2013-05-13T17:09:00', '2013-05-13T17:51:00')
swap_wavelength = a.Wavelength(174*u.angstrom)
swap_instrument = a.Instrument('SWAP')

# STEREO/EUVI observations for STEREO-A and STEREO-B
euvi_a_time_range = a.Time('2013-05-13T13:30:00', '2013-05-13T20:30:00')
euvi_b_time_range = a.Time('2013-05-13T13:30:00', '2013-05-13T20:30:00')
euvi_wavelengths = (a.Wavelength(195*u.angstrom) | a.Wavelength(304*u.angstrom) | 
                    a.Wavelength(284*u.angstrom))
euvi_instrument = a.Instrument('EUVI')

# SOHO/LASCO observations
lasco_time_range_c2 = a.Time('2013-05-13T17:24:00', '2013-05-13T19:54:00')
lasco_time_range_c3 = a.Time('2013-05-13T18:18:00', '2013-05-13T19:54:00')
lasco_instrument = a.Instrument('LASCO')
lasco_detector_c2 = a.Detector('C2')
lasco_detector_c3 = a.Detector('C3')

# STEREO/COR1 and COR2 observations for STEREO-A and STEREO-B
cor_time_range_a = a.Time('2013-05-13T17:25:00', '2013-05-13T20:24:00')
cor_time_range_b = a.Time('2013-05-13T17:10:00', '2013-05-13T20:09:00')
cor_instrument = a.Instrument('COR')

# Perform the queries for each instrument
aia_query = Fido.search(aia_time_range, aia_instrument, aia_wavelengths)
swap_query = Fido.search(swap_time_range, swap_instrument, swap_wavelength)
euvi_a_query = Fido.search(euvi_a_time_range, euvi_instrument, euvi_wavelengths)
euvi_b_query = Fido.search(euvi_b_time_range, euvi_instrument, euvi_wavelengths)
lasco_c2_query = Fido.search(lasco_time_range_c2, lasco_instrument, lasco_detector_c2)
lasco_c3_query = Fido.search(lasco_time_range_c3, lasco_instrument, lasco_detector_c3)
cor_a_query = Fido.search(cor_time_range_a, cor_instrument)
cor_b_query = Fido.search(cor_time_range_b, cor_instrument)

# Display the query results for each instrument
print("Query for SDO/AIA observations:")
print(aia_query)
print("Query for PROBA2/SWAP observations:")
print(swap_query)
print("Query for STEREO/EUVI-A observations:")
print(euvi_a_query)
print("Query for STEREO/EUVI-B observations:")
print(euvi_b_query)
print("Query for SOHO/LASCO C2 observations:")
print(lasco_c2_query)
print("Query for SOHO/LASCO C3 observations:")
print(lasco_c3_query)
print("Query for STEREO/COR1 and COR2 on STEREO-A observations:")
print(cor_a_query)
print("Query for STEREO/COR1 and COR2 on STEREO-B observations:")
print(cor_b_query)

# Uncomment the lines below to download the data
# a
