# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for calibration between SDO/HMI and SOHO/MDI
start_cr = 2097  # Start Carrington Rotation
end_cr = 2104    # End Carrington Rotation

# SOHO/MDI: Magnetic field strength and configuration
mdi_instrument = a.Instrument("MDI")
mdi_wavelength = a.Wavelength(6768 * u.Angstrom)
mdi_physobs = a.Physobs("LOS_magnetic_field")
mdi_time_range = a.Time("1996-01-30T00:00:00", "2011-04-12T23:59:59")  # Full available time range for MDI

# SDO/HMI: Magnetic field strength and configuration
hmi_instrument = a.Instrument("HMI")
hmi_wavelength = a.Wavelength(6173 * u.Angstrom)
hmi_physobs = a.Physobs("LOS_magnetic_field")
hmi_time_range = a.Time("2010-05-01T00:00:00", "present")  # Full available time range for HMI

# Construct queries for both instruments
mdi_query = Fido.search(mdi_time_range, mdi_instrument, mdi_wavelength, mdi_physobs)
hmi_query = Fido.search(hmi_time_range, hmi_instrument, hmi_wavelength, hmi_physobs)

# Display the query results for both instruments
print("Query for SOHO/MDI data:")
print(mdi_query)
print("Query for SDO/HMI data:")
print(hmi_query)

# Uncomment the lines below to download the data
# mdi_files = Fido.fetch(mdi_query)
# hmi_files = Fido.fetch(hmi_query)
