# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the broad time range for STEREO HI1 observations from 1997 to 2022
stereo_time_range = a.Time('1997-01-01', '2022-12-31')

# Define the specific time range for SOHO LASCO observations in May 2022
lasco_time_range = a.Time('2022-05-13T00:00:00', '2022-05-17T23:59:59')

# Wavelength ranges for STEREO HI1 and SOHO LASCO
stereo_wavelength = a.Wavelength(615 * u.nm, 740 * u.nm)
lasco_orange_wavelength = a.Wavelength(540 * u.nm, 620 * u.nm)
lasco_clear_wavelength = a.Wavelength(530 * u.nm, 840 * u.nm)
lasco_blue_wavelength = a.Wavelength(450 * u.nm, 500 * u.nm)  # Assuming range for blue filter

# Instruments
secchi = a.Instrument("SECCHI")
hi1_detector = a.Detector("HI1")
lasco = a.Instrument("LASCO")
c2 = a.Detector("C2")
c3 = a.Detector("C3")

# Perform the queries
stereo_query = Fido.search(stereo_time_range, secchi, hi1_detector, stereo_wavelength)

lasco_c2_query_orange = Fido.search(lasco_time_range, lasco, c2, lasco_orange_wavelength)
lasco_c2_query_clear = Fido.search(lasco_time_range, lasco, c2, lasco_clear_wavelength)

lasco_c3_query_orange = Fido.search(lasco_time_range, lasco, c3, lasco_orange_wavelength)
lasco_c3_query_clear = Fido.search(lasco_time_range, lasco, c3, lasco_clear_wavelength)
lasco_c3_query_blue = Fido.search(lasco_time_range, lasco, c3, lasco_blue_wavelength)

# Display the query results
print("Query for STEREO-A and STEREO-B HI1 observations:")
print(stereo_query)

print("Query for SOHO LASCO C2 Orange observations:")
print(lasco_c2_query_orange)
print("Query for SOHO LASCO C2 Clear observations:")
print(lasco_c2_query_clear)

print("Query for SOHO LASCO C3 Orange observations:")
print(lasco_c3_query_orange)
print("Query for SOHO LASCO C3 Clear observations:")
print(lasco_c3_query_clear)
print("Query for SOHO LASCO C3 Blue observations:")
print(lasco_c3_query_blue)

# Uncomment the lines below to download the data
# stereo_files = Fido.fetch(stereo_query)
# lasco_c2_orange_files = Fido.fetch(lasco_c2_query_orange)
# lasco_c2_clear_files = Fido.fetch(lasco_c2_query_clear)
# lasco_c3_orange_files = Fido.fetch(lasco_c3_query_orange)
# lasco_c3_clear_files = Fido.fetch(lasco_c3_query_clear)
# lasco_c3_blue_files = Fido.fetch(lasco_c3_query_blue)
