# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the full operational period of SWAN on SOHO as per the VSO interface
swan_start_date = '1996-01-12'
swan_end_date = 'present'  # Using 'present' to cover all available data up to the current date

# Time range for SWAN observations
swan_time_range = a.Time(swan_start_date, swan_end_date)

# SWAN instrument on SOHO
swan_instrument = a.Instrument("SWAN")

# Wavelength for Solar Lyα line as mentioned in the context
swan_wavelength = a.Wavelength(1215.6 * u.angstrom)

# Construct the query for SWAN data
swan_query = Fido.search(swan_time_range, swan_instrument, swan_wavelength)

# Display the query results for SWAN
print("Query for SWAN data on SOHO:")
print(swan_query)

# Uncomment the line below to download the data
# swan_files = Fido.fetch(swan_query)
