# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# AIA observations of the prominence eruption
aia_time_range = a.Time('2013-12-04T04:37:00', '2013-12-04T04:45:00')
aia_instrument = a.Instrument("AIA")
aia_wavelengths = a.Wavelength(304 * u.angstrom) | a.Wavelength(171 * u.angstrom) | a.Wavelength(193 * u.angstrom)
aia_query = Fido.search(aia_time_range, aia_instrument, aia_wavelengths)

# LASCO observations of the CME in the outer corona
lasco_time_range = a.Time('2013-12-04T05:12:00', '2013-12-04T23:59:59')  # End time is assumed for the day
lasco_instrument = a.Instrument("LASCO")
lasco_query = Fido.search(lasco_time_range, lasco_instrument)

# SECCHI observations for CME propagation analysis
secchi_time_range = a.Time('2013-12-04T00:00:00', '2013-12-04T23:59:59')  # Full day range for SECCHI data
secchi_instrument = a.Instrument("SECCHI")
secchi_query = Fido.search(secchi_time_range, secchi_instrument)

# Display the query results
print("Query for AIA observations of the prominence eruption:")
print(aia_query)
print("Query for LASCO observations of the CME in the outer corona:")
print(lasco_query)
print("Query for SECCHI observations of CME propagation:")
print(secchi_query)

# Uncomment the lines below to download the data
# aia_files = Fido.fetch(aia_query)
# lasco_files = Fido.fetch(lasco_query)
# secchi_files = Fido.fetch(secchi_query)
