# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for MDI overlapping with HMI
mdi_start_date = '2010-04-01'
mdi_end_date = '2011-04-01'
mdi_time_range = a.Time(mdi_start_date, mdi_end_date)

# Define the observation periods for GONG overlapping with HMI (even years 2010-2018)
gong_years = ['2010', '2012', '2014', '2016', '2018']
gong_time_ranges = [a.Time(f"{year}-01-01", f"{year}-12-31") for year in gong_years]

# Instruments and their attributes
mdi_instrument = a.Instrument("MDI")
gong_instrument = a.Instrument("GONG")
wavelength = a.Wavelength(6768 * u.angstrom)
physobs = a.Physobs("LOS_magnetic_field")

# Constructing the query for MDI
mdi_query = Fido.search(mdi_time_range, mdi_instrument, wavelength, physobs)

# Constructing the queries for GONG for each specified year
gong_queries = [Fido.search(time_range, gong_instrument, wavelength, physobs) for time_range in gong_time_ranges]

# Display the query results
print("Query for MDI observations:")
print(mdi_query)
for year, query in zip(gong_years, gong_queries):
    print(f"Query for GONG observations in {year}:")
    print(query)

# Uncomment the lines below to download the data
# mdi_files = Fido.fetch(mdi_query)
# for query in gong_queries:
#     gong_files = Fido.fetch(query)
