# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation date for the ESP event
observation_date = "2012-07-14"

# ACE/EPAM: Measures ion and electron intensities
ace_epam_time_range = a.Time(observation_date + "T00:00:00", observation_date + "T23:59:59")
ace_epam_instrument = a.Instrument("ACE/EPAM")
ace_epam_physobs = a.Physobs("ion_intensity")

# SoHO/ERNE: Measures flux of solar energetic particles
soho_erne_time_range = a.Time(observation_date + "T00:00:00", observation_date + "T23:59:59")
soho_erne_instrument = a.Instrument("SoHO/ERNE")
soho_erne_physobs = a.Physobs("proton_intensity")

# Constructing the queries
ace_epam_query = Fido.search(ace_epam_time_range, ace_epam_instrument, ace_epam_physobs)
soho_erne_query = Fido.search(soho_erne_time_range, soho_erne_instrument, soho_erne_physobs)

# Display the query results
print("Query for ACE/EPAM ion intensity data:")
print(ace_epam_query)
print("Query for SoHO/ERNE proton intensity data:")
print(soho_erne_query)

# Uncomment the lines below to download the data
# ace_epam_files = Fido.fetch(ace_epam_query)
# soho_erne_files = Fido.fetch(soho_erne_query)
