# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a

# Define the observation period for MDI on SOHO
mdi_start_date = '1996-01-01'
mdi_end_date = '2001-12-31'
mdi_time_range = a.Time(mdi_start_date, mdi_end_date)

# Instrument details
mdi_instrument = a.Instrument("MDI")

# Construct the query for MDI data
mdi_query = Fido.search(mdi_time_range, mdi_instrument)

# Display the query results for MDI
print("Query for MDI on SOHO:")
print(mdi_query)

# Uncomment the line below to download the data
# mdi_files = Fido.fetch(mdi_query)

# Define the observation period for SOT on Hinode
# Note: Exact dates are not specified, so we assume a broad range around the publication year
sot_start_date = '2010-01-01'
sot_end_date = '2012-12-31'
sot_time_range = a.Time(sot_start_date, sot_end_date)

# Instrument details
sot_instrument = a.Instrument("SOT")

# Construct the query for SOT data
sot_query = Fido.search(sot_time_range, sot_instrument)

# Display the query results for SOT
print("Query for SOT on Hinode:")
print(sot_query)

# Uncomment the line below to download the data
# sot_files = Fido.fetch(sot_query)
