# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period as specified in the context
start_date = '2014-11-01'
end_date = '2022-09-30'

# Time range for the entire observation period
time_range = a.Time(start_date, end_date)

# K-Coronagraph (K-Cor) on MLSO: Used for observing CME kinematics
kcor_instrument = a.Instrument("K-Cor")

# Since the physical observable related to velocity and acceleration is not directly available,
# we use intensity as a proxy to fetch the relevant data.
kcor_query = Fido.search(time_range, kcor_instrument)

# Display the query results
print("Query for K-Coronagraph (K-Cor) Data:")
print(kcor_query)

# Uncomment the line below to download the data
# kcor_files = Fido.fetch(kcor_query)
