# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation date for the SEP event
observation_date = "2020-05-29"

# EPI-Hi on Parker Solar Probe: Measures energetic protons and heavy ions
epi_hi_time_range = a.Time(observation_date)
epi_hi_instrument = a.Instrument("EPI-Hi")
epi_hi_query = Fido.search(epi_hi_time_range, epi_hi_instrument)
print("Query for EPI-Hi observations on Parker Solar Probe:")
print(epi_hi_query)

# LET on STEREO-A: Measures proton intensities in specific energy ranges
let_time_range = a.Time(observation_date)
let_instrument = a.Instrument("LET")
let_query = Fido.search(let_time_range, let_instrument)
print("Query for LET observations on STEREO-A:")
print(let_query)

# SEPT on STEREO-A: Measures lower energy protons
sept_time_range = a.Time(observation_date)
sept_instrument = a.Instrument("SEPT")
sept_query = Fido.search(sept_time_range, sept_instrument)
print("Query for SEPT observations on STEREO-A:")
print(sept_query)

# Uncomment the lines below to download the data
# epi_hi_files = Fido.fetch(epi_hi_query)
# let_files = Fido.fetch(let_query)
# sept_files = Fido.fetch(sept_query)
