# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period as mentioned in the context
start_date = '2010-01-01'
end_date = '2015-12-31'

# Time range for the entire observation period
time_range = a.Time(start_date, end_date)

# SDO/HMI: Vector magnetic field data
hmi_query = Fido.search(time_range, a.Instrument("HMI"), a.Physobs("vector_magnetic_field"))

# SDO/AIA: UV images at 1600 Å for flare ribbon identification
aia_query = Fido.search(time_range, a.Instrument("AIA"), a.Wavelength(1600 * u.Angstrom))

# Display the query results
print("Query for SDO/HMI Vector Magnetic Field Data:")
print(hmi_query)
print("Query for SDO/AIA 1600 Å UV Images:")
print(aia_query)

# Uncomment the lines below to download the data
# hmi_files = Fido.fetch(hmi_query)
# aia_files = Fido.fetch(aia_query)
