# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the specific observation time for each instrument
aia_time_range = a.Time('2012-03-13T16:00:00', '2012-03-13T17:59:00')
secchi_time_range = a.Time('2012-03-13T00:00:00', '2012-03-13T23:59:59')
rhessi_time_range = a.Time('2012-03-13T16:00:00', '2012-03-13T16:20:00')
lasco_time_range = a.Time('2012-03-13T00:00:00', '2012-03-13T23:59:59')
goes_time_range = a.Time('2012-03-13T00:00:00', '2012-03-13T23:59:59')
hmi_time_range = a.Time('2012-03-13T00:00:00', '2012-03-13T23:59:59')

# Define the instruments and their specific wavelengths or observables
aia_query = Fido.search(
    aia_time_range, 
    a.Instrument("AIA"), 
    a.Wavelength(131 * u.angstrom) | a.Wavelength(94 * u.angstrom) | 
    a.Wavelength(171 * u.angstrom) | a.Wavelength(193 * u.angstrom) | 
    a.Wavelength(211 * u.angstrom) | a.Wavelength(335 * u.angstrom) | 
    a.Wavelength(304 * u.angstrom) | a.Wavelength(1600 * u.angstrom) | 
    a.Wavelength(1700 * u.angstrom)
)

secchi_query = Fido.search(secchi_time_range, a.Instrument("SECCHI"))

rhessi_query = Fido.search(
    rhessi_time_range, 
    a.Instrument("RHESSI"), 
    a.Wavelength("<12 keV")
)

lasco_query = Fido.search(lasco_time_range, a.Instrument("LASCO"))

goes_query = Fido.search(goes_time_range, a.Instrument("XRS"))

hmi_query = Fido.search(hmi_time_range, a.Instrument("HMI"))

# Print the query results
print("Query for AIA observations:")
print(aia_query)
print("Query for SECCHI observations:")
print(secchi_query)
print("Query for RHESSI observations:")
print(rhessi_query)
print("Query for LASCO observations:")
print(lasco_query)
print("Query for GOES observations:")
print(goes_query)
print("Query for HMI observations:")
print(hmi_query)

# Uncomment the lines below to download the data
# aia_files = Fido.fetch(aia_query)
# secchi_files = Fido.fetch(secchi_query)
# rhessi_files = Fido.fetch(rhessi_query)
# lasco_files = Fido.fetch(lasco_query)
# goes_files = Fido.fetch(goes_query)
# hmi_files = Fido.fetch(hmi_query)
