# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a

# Define the observation period as specified in the context
start_time = '2003-04-15T21:35:00'
end_time = '2003-05-13T03:24:00'
time_range = a.Time(start_time, end_time)

# Wind spacecraft data query for magnetic fields, bulk plasma, and heavy ion composition
wind_instrument = a.Instrument('WIND')
wind_physobs = a.Physobs('magnetic_field')  # Assuming 'magnetic_field' covers all needed physical observables
wind_query = Fido.search(time_range, wind_instrument, wind_physobs)

# ACE spacecraft data query for ionic and elemental composition
ace_instrument = a.Instrument('ACE')
ace_physobs = a.Physobs('ionic_composition')  # Assuming 'ionic_composition' covers the needed physical observables
ace_query = Fido.search(time_range, ace_instrument, ace_physobs)

# Display the query results
print("Query for Wind spacecraft data:")
print(wind_query)
print("Query for ACE spacecraft data:")
print(ace_query)

# Uncomment the lines below to download the data
# wind_files = Fido.fetch(wind_query)
# ace_files = Fido.fetch(ace_query)
