# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for MDI, EIT, and LASCO as mentioned in the context
mdi_time_range = a.Time('1996-05-01', '2011-04-12')
eit_time_range = a.Time('1996-01-01', 'ongoing')
lasco_time_range = a.Time('1995-12-08', 'ongoing')

# MDI: Observing the solar photosphere
mdi_query = Fido.search(mdi_time_range, a.Instrument("MDI"), a.Wavelength(6768 * u.Angstrom))

# EIT: Imaging the solar atmosphere to low corona
eit_query = Fido.search(eit_time_range, a.Instrument("EIT"), a.Wavelength(195 * u.Angstrom))

# LASCO: Observing the solar corona
lasco_query = Fido.search(lasco_time_range, a.Instrument("LASCO"), a.Detector("C2"))

# Display the query results for each instrument
print("Query for MDI observations of the solar photosphere:")
print(mdi_query)
print("Query for EIT observations of the solar atmosphere to low corona:")
print(eit_query)
print("Query for LASCO observations of the solar corona:")
print(lasco_query)

# Uncomment the lines below to download the data
# mdi_files = Fido.fetch(mdi_query)
# eit_files = Fido.fetch(eit_query)
# lasco_files = Fido.fetch(lasco_query)
