# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

import astropy.units as u
from sunpy.net import Fido
from sunpy.net import attrs as a

# Define the time ranges for the queries
time_range_messenger = a.Time('2010-02-07', '2015-04-30')

# Query for SDO/AIA data
print("Querying SDO/AIA data...")
# Using smaller example time range due to potential broad time range issue
time_range_sdo_aia = a.Time('2010-02-07', '2010-02-14')  # Example time range within the original range
query_sdo_aia = Fido.search(
    time_range_sdo_aia, 
    a.Instrument('AIA'), 
    a.Source('SDO')
)
print(query_sdo_aia)
# Uncomment the following line to fetch the data
# files_sdo_aia = Fido.fetch(query_sdo_aia)

# Query for SOHO/LASCO data
print("Querying SOHO/LASCO data...")
query_soho_lasco = Fido.search(
    time_range_messenger, 
    a.Instrument('LASCO'), 
    a.Source('SOHO')
)
print(query_soho_lasco)
# Note: The query returns a large number of results, indicating pagination.
# Uncomment the following line to fetch the data
# files_soho_lasco = Fido.fetch(query_soho_lasco)

# Query for STEREO/SECCHI data
print("Querying STEREO/SECCHI data...")
query_stereo_secchi = Fido.search(
    time_range_messenger, 
    a.Instrument('SECCHI'), 
    a.Detector('COR1'),  # Example detector, adjust as needed
    a.Source('STEREO')
)
print(query_stereo_secchi)
# Note: The query returns a large number of results, indicating pagination.
# Uncomment the following line to fetch the data
# files_stereo_secchi = Fido.fetch(query_stereo_secchi)

# Query for GOES data
print("Querying GOES data...")
query_goes = Fido.search(
    time_range_messenger, 
    a.Instrument('XRS'), 
    a.Source('GOES')
)
print(query_goes)
# Note: The query returns a large number of results, indicating pagination.
# Uncomment the following line to fetch the data
# files_goes = Fido.fetch(query_goes)
