# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

# Import necessary libraries from SunPy
from sunpy.net import Fido, attrs as a
import sunpy.time

# Define the time range for the ADAPT-GONG magnetograms
start_time_adapt_gong = "2007-01-01"  # Example time range may be too broad
end_time_adapt_gong = "2022-02-28"    # Consider using a smaller range for better results
# Example of a smaller time range: 
# start_time_adapt_gong = "2021-01-01"
# end_time_adapt_gong = "2021-01-31"

# Define the time range for the SOHO-LASCO observations
start_time_lasco = "2008-01-01"
end_time_lasco = "2020-12-31"

# Create a query for ADAPT-GONG magnetograms
adapt_gong_query = Fido.search(
    a.Time(start_time_adapt_gong, end_time_adapt_gong),
    a.Instrument('ADAPT-GONG')
)

# Create a query for SOHO-LASCO observations
lasco_query = Fido.search(
    a.Time(start_time_lasco, end_time_lasco),
    a.Instrument('LASCO')
)

# Print the results of the queries
print("ADAPT-GONG Magnetograms Query Results:")
print(adapt_gong_query)  # Note: Results may be empty due to broad time range

print("\nSOHO-LASCO Query Results:")
print(lasco_query)  # Warning: This may have many results (pagination may be needed)

# Uncomment the following lines to fetch the data
# adapt_gong_data = Fido.fetch(adapt_gong_query)
# lasco_data = Fido.fetch(lasco_query)
