# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for SOHO/MDI
mdi_start_date = '1996-05-01'
mdi_end_date = '2010-05-31'
mdi_time_range = a.Time(mdi_start_date, mdi_end_date)

# Define the observation period for SDO/HMI
hmi_start_date = '2010-06-01'
hmi_end_date = '2022-12-31'
hmi_time_range = a.Time(hmi_start_date, hmi_end_date)

# SOHO/MDI: Observing solar magnetic fields
mdi_instrument = a.Instrument("MDI")
mdi_physobs = a.Physobs("LOS_magnetic_field")  # Line-of-sight magnetic field

# SDO/HMI: Continuation of solar magnetic field observations
hmi_instrument = a.Instrument("HMI")
hmi_physobs = a.Physobs("LOS_magnetic_field")  # Line-of-sight magnetic field

# Construct queries for MDI and HMI
mdi_query = Fido.search(mdi_time_range, mdi_instrument, mdi_physobs)
hmi_query = Fido.search(hmi_time_range, hmi_instrument, hmi_physobs)

# Display the query results for MDI and HMI
print("Query for SOHO/MDI observations of solar magnetic fields:")
print(mdi_query)
print("Query for SDO/HMI observations of solar magnetic fields:")
print(hmi_query)

# Uncomment the lines below to download the data
# mdi_files = Fido.fetch(mdi_query)
# hmi_files = Fido.fetch(hmi_query)
