# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period around the 2011 November 3 CME event
start_date = '2011-11-01'
end_date = '2011-11-05'

# Time range for the entire observation period
time_range = a.Time(start_date, end_date)

# SOHO/LASCO for CME observations
# LASCO C2 and C3 are typically used for observing the outer corona
lasco_instrument = a.Instrument("LASCO")
detector_c2 = a.Detector("C2")
detector_c3 = a.Detector("C3")

# SDO/HMI for solar photospheric magnetic fields
hmi_instrument = a.Instrument("HMI")
hmi_observable = a.Physobs("LOS_magnetic_field")

# Construct queries for LASCO C2, C3 and SDO/HMI
lasco_c2_query = Fido.search(time_range, lasco_instrument, detector_c2)
lasco_c3_query = Fido.search(time_range, lasco_instrument, detector_c3)
hmi_query = Fido.search(time_range, hmi_instrument, hmi_observable)

# Display the query results for LASCO C2, C3 and SDO/HMI
print("Query for LASCO C2 Detector Data:")
print(lasco_c2_query)
print("Query for LASCO C3 Detector Data:")
print(lasco_c3_query)
print("Query for SDO/HMI Photospheric Magnetic Field Data:")
print(hmi_query)

# Uncomment the lines below to download the data
# lasco_c2_files = Fido.fetch(lasco_c2_query)
# lasco_c3_files = Fido.fetch(lasco_c3_query)
# hmi_files = Fido.fetch(hmi_query)
