# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation date
observation_date = "2013-10-25"  # Replace YYYY-MM-DD with the specific date of observation

# Solar Dynamics Observatory (SDO) query for EUV images
sdo_time_range = a.Time(observation_date + "T00:00:00", observation_date + "T23:59:59")
sdo_wavelengths = [211 * u.Angstrom]  # AIA 211 Å channel
sdo_query = Fido.search(sdo_time_range, a.Instrument("AIA"), a.Wavelength(sdo_wavelengths[0]))

# Solar Terrestrial Relations Observatory (STEREO) query for EUVI images
stereo_time_range = a.Time(observation_date + "T00:00:00", observation_date + "T23:59:59")
stereo_wavelengths_euvi = [195 * u.Angstrom]  # EUVI 195 Å channel
stereo_query_euvi = Fido.search(stereo_time_range, a.Instrument("SECCHI"), a.Detector("EUVI"), a.Wavelength(stereo_wavelengths_euvi[0]))

# Solar Terrestrial Relations Observatory (STEREO) query for white-light images (COR1)
stereo_query_cor1 = Fido.search(stereo_time_range, a.Instrument("SECCHI"), a.Detector("COR1"))

# Solar Terrestrial Relations Observatory (STEREO) query for white-light images (COR2)
stereo_query_cor2 = Fido.search(stereo_time_range, a.Instrument("SECCHI"), a.Detector("COR2"))

# Print the query results
print("Query for SDO EUV images at 211 Å:")
print(sdo_query)
print("Query for STEREO EUVI images at 195 Å:")
print(stereo_query_euvi)
print("Query for STEREO white-light images (COR1):")
print(stereo_query_cor1)
print("Query for STEREO white-light images (COR2):")
print(stereo_query_cor2)

# Download the data
sdo_files = Fido.fetch(sdo_query)
stereo_files_euvi = Fido.fetch(stereo_query_euvi)
stereo_files_cor1 = Fido.fetch(stereo_query_cor1)
stereo_files_cor2 = Fido.fetch(stereo_query_cor2)

# Print the paths to the downloaded files
print("SDO files downloaded:")
print(sdo_files)
print("STEREO EUVI files downloaded:")
print(stereo_files_euvi)
print("STEREO COR1 files downloaded:")
print(stereo_files_cor1)
print("STEREO COR2 files downloaded:")
print(stereo_files_cor2)
