# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define a general observation date
observation_date = "YYYY-MM-DD"  # Replace YYYY-MM-DD with the specific date of observation

# Nançay Radioheliograph (NRH) query for radio emission at 150 MHz and 173 MHz
nrh_time_range = a.Time(observation_date + "T00:00:00", observation_date + "T23:59:59")
nrh_frequencies = [150 * u.MHz, 173 * u.MHz]
nrh_query = Fido.search(nrh_time_range, a.Instrument("NRH"), a.Wavelength(nrh_frequencies[0]) | a.Wavelength(nrh_frequencies[1]))

# Solar Dynamics Observatory (SDO) query for EUV images
sdo_time_range = a.Time(observation_date + "T00:00:00", observation_date + "T23:59:59")
sdo_wavelengths = [211 * u.Angstrom]  # AIA 211 Å channel
sdo_query = Fido.search(sdo_time_range, a.Instrument("AIA"), a.Wavelength(sdo_wavelengths[0]))

# Solar Terrestrial Relations Observatory (STEREO) query for EUV and white-light images
stereo_time_range = a.Time(observationation_date + "T00:00:00", observation_date + "T23:59:59")
stereo_wavelengths = [195 * u.Angstrom]  # EUVI 195 Å channel
stereo_query = Fido.search(stereo_time_range, a.Instrument("SECCHI"), a.Wavelength(stereo_wavelengths[0]))

# Print the query results
print("Query for NRH radio emission at 150 MHz and 173 MHz:")
print(nrh_query)
print("Query for SDO EUV images at 211 Å:")
print(sdo_query)
print("Query for STEREO EUV images at 195 Å:")
print(stereo_query)

# Uncomment the lines below to download the data
# nrh_files = Fido.fetch(nrh_query)
# sdo_files = Fido.fetch(sdo_query)
# stereo_files = Fido.fetch(stereo_query)
