# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for SDO/AIA and SDO/HMI
aia_hmi_start_time = '2012-03-06T00:00:00'
aia_hmi_end_time = '2012-03-10T19:00:00'
aia_hmi_time_range = a.Time(aia_hmi_start_time, aia_hmi_end_time)

# AIA instrument details
aia_instrument = a.Instrument("AIA")
aia_wavelengths = a.Wavelength(94 * u.angstrom, 335 * u.angstrom)  # Example range covering some AIA channels

# HMI instrument details
hmi_instrument = a.Instrument("HMI")
hmi_wavelengths = a.Wavelength(6173 * u.angstrom)  # Typical HMI wavelength

# LASCO instrument details for three specific eruption times
lasco_instrument = a.Instrument("LASCO")
# Choose short time ranges
lasco_times = [
    a.Time('2012-03-07T01:30:00', '2012-03-07T01:35:00'), 
    a.Time('2012-03-09T04:26:00', '2012-03-09T04:31:00'), 
    a.Time('2012-03-10T18:00:00', '2012-03-10T18:05:00')
]


# Construct queries for AIA and HMI
aia_query = Fido.search(aia_hmi_time_range, aia_instrument, aia_wavelengths)
hmi_query = Fido.search(aia_hmi_time_range, hmi_instrument, hmi_wavelengths)

# Construct queries for LASCO at specific times
lasco_queries = [Fido.search(time, lasco_instrument) for time in lasco_times]

# Display the query results
print("Query for SDO/AIA observations:")
print(aia_query)
print("Query for SDO/HMI observations:")
print(hmi_query)
for i, lasco_query in enumerate(lasco_queries, 1):
    print(f"Query for LASCO observation during eruption {i}:")
    print(lasco_query)

# Uncomment the lines below to download the data
# aia_files = Fido.fetch(aia_query)
# hmi_files = Fido.fetch(hmi_query)
# lasco_files = [Fido.fetch(query) for query in lasco_queries]
