# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

import sunpy.net.vso as vso
from sunpy.net import Fido, attrs as a
import astropy.units as u

# Initialize VSO client
client = vso.VSOClient()

# Data Collection Period 1: FSI on board Solar Orbiter
print("Querying FSI data for 2021 September 9, 00:42 UT – 2021 September 9, 09:30 UT")
query1 = Fido.search(
    a.Time('2021-09-09 00:42', '2021-09-09 09:30'),
    a.Instrument('EUI'),
    a.Wavelength(17.4 * u.nm)
)
print(query1)  # Check for pagination issues

# Data Collection Period 2: FSI on board Solar Orbiter
print("Querying FSI data for 2021 November 1, 00:42 UT – 2021 November 3, 23:42 UT")
query2 = Fido.search(
    a.Time('2021-11-01 00:42', '2021-11-03 23:42'),
    a.Instrument('EUI'),
    a.Wavelength(17.4 * u.nm)
)
print(query2)  # Check for pagination issues

# Data Collection Period 3: FSI on board Solar Orbiter
print("Querying FSI data for 2022 February 8, 04:15 UT – 2022 February 8, 07:45 UT")
query3 = Fido.search(
    a.Time('2022-02-08 04:15', '2022-02-08 07:45'),
    a.Instrument('EUI'),
    a.Wavelength(17.4 * u.nm)
)
print(query3)  # Check for pagination issues

# Data Collection Period 4: FSI on board Solar Orbiter
print("Querying FSI data for 2022 March 7, 16:00 UT – 2022 March 7, 19:30 UT")
query4 = Fido.search(
    a.Time('2022-03-07 16:00', '2022-03-07 19:30'),
    a.Instrument('EUI'),
    a.Wavelength(17.4 * u.nm)
)
print(query4)  # Check for pagination issues

# Data Collection Period 5: FSI on board Solar Orbiter
print("Querying FSI data for 2022 December 5, 04:00 UT – 2023 January 1, 21:36 UT")
# Using smaller example time range due to potential broad time range issue
query5 = Fido.search(
    a.Time('2022-12-05 04:00', '2022-12-10 04:00'),  # Example smaller time range
    a.Instrument('EUI'),
    a.Wavelength(17.4 * u.nm)
)
print(query5)  # Check for pagination issues

# Data Collection Period 1: Metis on board Solar Orbiter
print("Querying Metis data for 2021 November 1, 00:42 UT – 2021 November 3, 23:42 UT")
# Using smaller example time range due to potential broad time range issue
query6 = Fido.search(
    a.Time('2021-11-01 00:42', '2021-11-02 00:42'),  # Example smaller time range
    a.Instrument('Metis'),
    a.Wavelength(121.6 * u.nm)
)
print(query6)  # Check for pagination issues

# Data Collection Period 2: Metis on board Solar Orbiter
print("Querying Metis data for 2022 December 5, 04:00 UT – 2023 January 1, 21:36 UT")
# Using smaller example time range due to potential broad time range issue
query7 = Fido.search(
    a.Time('2022-12-05 04:00', '2022-12-10 04:00'),  # Example smaller time range
    a.Instrument('Metis'),
    a.Wavelength(121.6 * u.nm)
)
print(query7)  # Check for pagination issues

# Data Collection Period 1: LASCO on board SOHO
print("Querying LASCO data for 2021 November 1, 00:42 UT – 2021 November 3, 23:42 UT")
# Using smaller example time range due to potential broad time range issue
query8 = Fido.search(
    a.Time('2021-11-01 00:42', '2021-11-02 00:42'),  # Example smaller time range
    a.Instrument('LASCO'),
    a.Wavelength(500 * u.nm)  # Assuming visible light is around 500 nm
)
print(query8)  # Check for pagination issues

# Data Collection Period 2: LASCO on board SOHO
print("Querying LASCO data for 2022 March 7, 16:00 UT – 2022 March 7, 19:30 UT")
query9 = Fido.search(
    a.Time('2022-03-07 16:00', '2022-03-07 19:30'),
    a.Instrument('LASCO'),
    a.Wavelength(500 * u.nm)  # Assuming visible light is around 500 nm
)
print(query9)  # Check for pagination issues
