# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a

# Define the observation period for LASCO C2 and C3 on SOHO
lasco_c2_c3_start_date = '2013-01-01'
lasco_c2_c3_end_date = '2018-12-31'
lasco_c2_c3_time_range = a.Time(lasco_c2_c3_start_date, lasco_c2_c3_end_date)

# LASCO C2 and C3 on SOHO: Key instruments for observing CMEs
lasco_c2 = a.Instrument("LASCO") & a.Detector("C2")
lasco_c3 = a.Instrument("LASCO") & a.Detector("C3")

# Construct queries for LASCO C2 and C3
lasco_c2_query = Fido.search(lasco_c2_c3_time_range, lasco_c2)
lasco_c3_query = Fido.search(lasco_c2_c3_time_range, lasco_c3)

# Define the observation period for SECCHI COR2 on STEREO
secchi_cor2_start_date = '2007-01-01'
secchi_cor2_end_date = '2018-12-31'
secchi_cor2_time_range = a.Time(secchi_cor2_start_date, secchi_cor2_end_date)

# SECCHI COR2 on STEREO: Used for SEEDS catalog comparison
secchi_cor2 = a.Instrument("SECCHI") & a.Detector("COR2")

# Construct query for SECCHI COR2
secchi_cor2_query = Fido.search(secchi_cor2_time_range, secchi_cor2)

# Display the query results for LASCO C2, C3 and SECCHI COR2
print("Query for LASCO C2 Detector Data:")
print(lasco_c2_query)
print("Query for LASCO C3 Detector Data:")
print(lasco_c3_query)
print("Query for SECCHI COR2 Detector Data:")
print(secchi_cor2_query)

# Uncomment the lines below to download the data
# lasco_c2_files = Fido.fetch(lasco_c2_query)
# lasco_c3_files = Fido.fetch(lasco_c3_query)
# secchi_cor2_files = Fido.fetch(secchi_cor2_query)
