# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period for Nobeyama Radio Polarimeters (NoRP)
nor_start_date = '1994-06-01'
nor_end_date = '2023-12-31'  # Assuming present means the end of 2023 for the script
nor_time_range = a.Time(nor_start_date, nor_end_date)

# Frequencies for NoRP (in GHz, converted to wavelengths using c = f * lambda)
frequencies = [1, 2, 3.75, 9.4]  # GHz
wavelengths = [(3e8 / (freq * 1e9)) * u.m for freq in frequencies]  # Convert GHz to m

# SOHO and SDO data query for EUV and magnetic fields
soho_sdo_start_date = '1994-06-01'
soho_sdo_end_date = '2023-12-31'
soho_sdo_time_range = a.Time(soho_sdo_start_date, soho_sdo_end_date)
soho_instrument = a.Instrument('EIT')  # Example instrument for EUV
sdo_instrument = a.Instrument('HMI')  # Example instrument for magnetic fields

# GOES X-ray data query
goes_start_date = '1994-06-01'
goes_end_date = '2023-12-31'
goes_time_range = a.Time(goes_start_date, goes_end_date)
goes_instrument = a.Instrument('XRS')

# Perform the queries
# Note: NoRP data might need to be accessed via a different interface if not available in Fido
soho_query = Fido.search(soho_sdo_time_range, soho_instrument)
sdo_query = Fido.search(soho_sdo_time_range, sdo_instrument)
goes_query = Fido.search(goes_time_range, goes_instrument)

# Display the query results
print("Query for SOHO EUV data:")
print(soho_query)
print("Query for SDO magnetic field data:")
print(sdo_query)
print("Query for GOES X-ray data:")
print(goes_query)

# Uncomment the lines below to download the data
# soho_files = Fido.fetch(soho_query)
# sdo_files = Fido.fetch(sdo_query)
# goes_files = Fido.fetch(goes_query)
