# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# Define the observation period as mentioned in the context
start_date = '1995-01-01'
end_date = '2018-12-31'

# Time range for the entire observation period
time_range = a.Time(start_date, end_date)

# Nobeyama RadioHeliograph data at 17 GHz and 34 GHz
# Note: The actual availability of these specific frequencies needs to be confirmed as they might not be directly accessible via Fido.
norh_query_17ghz = Fido.search(time_range, a.Instrument("NoRH"), a.Wavelength(17 * u.GHz))
norh_query_34ghz = Fido.search(time_range, a.Instrument("NoRH"), a.Wavelength(34 * u.GHz))

# Display the query results
print("Query for Nobeyama RadioHeliograph at 17 GHz:")
print(norh_query_17ghz)
print("Query for Nobeyama RadioHeliograph at 34 GHz:")
print(norh_query_34ghz)

# Uncomment the lines below to download the data
# norh_files_17ghz = Fido.fetch(norh_query_17ghz)
# norh_files_34ghz = Fido.fetch(norh_query_34ghz)
