# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.
from sunpy.net import Fido, attrs as a

# SDO/EVE: Detailed measurements of the EUV solar spectrum
eve_time_range = a.Time('2010-05-01', '2020-02-29')
eve_instrument = a.Instrument("EVE")
eve_query = Fido.search(eve_time_range, eve_instrument)

# SDO/HMI: Full-disk magnetograms starting from May 2010
hmi_time_range = a.Time('2010-05-01', '2020-02-29')
hmi_instrument = a.Instrument("HMI")
hmi_query = Fido.search(hmi_time_range, hmi_instrument)

# SoHO/MDI: Full-disk magnetograms until April 12, 2011
mdi_time_range = a.Time('1996-01-01', '2011-04-12')
mdi_instrument = a.Instrument("MDI")
mdi_query = Fido.search(mdi_time_range, mdi_instrument)

# Display the query results
print("Query for SDO/EVE data:")
print(eve_query)
print("Query for SDO/HMI data:")
print(hmi_query)
print("Query for SoHO/MDI data:")
print(mdi_query)

# Uncomment the lines below to download the data
# eve_files = Fido.fetch(eve_query)
# hmi_files = Fido.fetch(hmi_query)
# mdi_files = Fido.fetch(mdi_query)
