# This script was generated by an AI model and has not been reviewed by a human expert. Please use with caution.

from sunpy.net import Fido, attrs as a
from astropy import units as u

# SORCE/XPS: Daily averaged Sun-as-a-star spectra from X-ray to shortward EUV band
xps_time_range = a.Time('2010-05-01', '2020-02-29')
xps_instrument = a.Instrument("XPS")
xps_wavelength = a.Wavelength(0.5 * u.nm, 33.3 * u.nm)
xps_query = Fido.search(xps_time_range, xps_instrument, xps_wavelength)

# SDO/EVE: Detailed measurements of the EUV solar spectrum
eve_time_range = a.Time('2010-05-01', '2020-02-29')
eve_instrument = a.Instrument("EVE")
eve_wavelength = a.Wavelength(33.3 * u.nm, 106.6 * u.nm)
eve_query = Fido.search(eve_time_range, eve_instrument, eve_wavelength)

# TIMED/SEE: Broad range of wavelengths covering X-ray, EUV, and FUV solar spectra
see_time_range = a.Time('2002-01-01', '2016-12-31')
see_instrument = a.Instrument("SEE")
see_wavelength = a.Wavelength(0.5 * u.nm, 180 * u.nm)
see_query = Fido.search(see_time_range, see_instrument, see_wavelength)

# Display the query results
print("Query for SORCE/XPS data:")
print(xps_query)
print("Query for SDO/EVE data:")
print(eve_query)
print("Query for TIMED/SEE data:")
print(see_query)

# Uncomment the lines below to download the data
# xps_files = Fido.fetch(xps_query)
# eve_files = Fido.fetch(eve_query)
# see_files = Fido.fetch(see_query)
